defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

runner: standard
debug: false
seed: 0
output_dir: examples/optuna_example_output
wandb_project: null
tensorboard_file: null
experiment_name: optuna_tuning_example
num_steps: 50_000 
env: pufferlib.ocean.bandit
env_kwargs: {}
env_wrappers: []
num_envs: 64

algorithm: PPO

algorithm_kwargs:
  rescale_action: False
  tanh_squash: False

  rollout_buffer_class:
    _target_: mighty.mighty_replay.MightyRolloutBuffer

  rollout_buffer_kwargs:
    buffer_size: 128        # (16 × 128 = 2048 total)
    gamma: 0.99
    gae_lambda: 0.95
    obs_shape: ???
    act_dim: ???
    n_envs: ???
    discrete_action: ???

  # Optimiser and update settings
  learning_rate: 3e-4
  batch_size: 2048        # 16 environments × 128 steps = 2048 total samples
  gamma: 0.99
  ppo_clip: 0.2
  value_loss_coef: 0.5
  entropy_coef: 0.01
  max_grad_norm: 0.5      # gradient clipping

  hidden_sizes: [256, 256]
  activation: "tanh"

  n_gradient_steps: 1     # one gradient step per rollout
  n_epochs: 10            # ten update epochs per rollout
  minibatch_size: 128     # 2048 ÷ 64 = 32 minibatches
  kl_target: null         # disable KL‑based early stopping
  use_value_clip: true

  policy_class: mighty.mighty_exploration.StochasticPolicy
  policy_kwargs:
    entropy_coefficient: 0.0


# Training
eval_every_n_steps: 1e4  # After how many steps to evaluate.
n_episodes_eval: 10
checkpoint: null  # Path to load model checkpoint
save_model_every_n_steps: 5e5

hydra:
  run:
    dir: ${output_dir}/${experiment_name}_${seed}
  sweep:
    dir: ${output_dir}/${experiment_name}_${seed}
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: optuna_tuning_example
    storage: null
    n_trials: 20
    n_jobs: 1
    params:
      algorithm_kwargs.learning_rate: range(0.0001, 0.05)
      algorithm_kwargs.batch_size: range(8, 128)