SEED=42

# Sample context sets for CARL CartPole
python examples/sample_carl_context_sets.py

# Run one training run for each context set
python mighty/run_mighty.py 'algorithm=ppo' 'env=CARLCartPole' seed=$SEED 'num_steps=250000' 'env_wrappers=[mighty.mighty_utils.wrappers.FlattenVecObs]' 'algorithm_kwargs.rollout_buffer_kwargs.buffer_size=2048' '+env_kwargs.load_contexts=examples/carl_generalization_example/context_sets/train_contexts_a.json' '+env_kwargs.load_eval_contexts=examples/carl_generalization_example/context_sets/eval_contexts_a.json' output_dir=examples/carl_generalization_example experiment_name=carl_cartpole_generalization_mode_a/seed
python mighty/run_mighty.py 'algorithm=ppo' 'env=CARLCartPole' seed=$SEED 'num_steps=250000' 'env_wrappers=[mighty.mighty_utils.wrappers.FlattenVecObs]' 'algorithm_kwargs.rollout_buffer_kwargs.buffer_size=2048' '+env_kwargs.load_contexts=examples/carl_generalization_example/context_sets/train_contexts_b.json' '+env_kwargs.load_eval_contexts=examples/carl_generalization_example/context_sets/eval_contexts_b.json' output_dir=examples/carl_generalization_example experiment_name=carl_cartpole_generalization_mode_b/seed
python mighty/run_mighty.py 'algorithm=ppo' 'env=CARLCartPole' seed=$SEED 'num_steps=250000' 'env_wrappers=[mighty.mighty_utils.wrappers.FlattenVecObs]' 'algorithm_kwargs.rollout_buffer_kwargs.buffer_size=2048' '+env_kwargs.load_contexts=examples/carl_generalization_example/context_sets/train_contexts_c.json' '+env_kwargs.load_eval_contexts=examples/carl_generalization_example/context_sets/eval_contexts_c.json' output_dir=examples/carl_generalization_example experiment_name=carl_cartpole_generalization_mode_c/seed

# Evaluate the trained agents on the test contexts
python mighty/evaluate_mighty.py 'algorithm=ppo' 'env=CARLCartPole' seed=$SEED 'env_wrappers=[mighty.mighty_utils.wrappers.FlattenVecObs]' 'algorithm_kwargs.rollout_buffer_kwargs.buffer_size=2048' '+env_kwargs.load_contexts=examples/carl_generalization_example/context_sets/train_contexts_a.json' '+env_kwargs.load_eval_contexts=examples/carl_generalization_example/context_sets/test_contexts.json' checkpoint=examples/carl_generalization_example/carl_cartpole_generalization_mode_a/seed_42/checkpoints/250000 output_dir=examples/carl_generalization_example experiment_name=carl_cartpole_generalization_mode_a/testing_seed
python mighty/evaluate_mighty.py 'algorithm=ppo' 'env=CARLCartPole' seed=$SEED 'env_wrappers=[mighty.mighty_utils.wrappers.FlattenVecObs]' 'algorithm_kwargs.rollout_buffer_kwargs.buffer_size=2048' '+env_kwargs.load_contexts=examples/carl_generalization_example/context_sets/train_contexts_a.json' '+env_kwargs.load_eval_contexts=examples/carl_generalization_example/context_sets/test_contexts.json' checkpoint=examples/carl_generalization_example/carl_cartpole_generalization_mode_b/seed_42/checkpoints/250000 output_dir=examples/carl_generalization_example experiment_name=carl_cartpole_generalization_mode_b/testing_seed
python mighty/evaluate_mighty.py 'algorithm=ppo' 'env=CARLCartPole' seed=$SEED 'env_wrappers=[mighty.mighty_utils.wrappers.FlattenVecObs]' 'algorithm_kwargs.rollout_buffer_kwargs.buffer_size=2048' '+env_kwargs.load_contexts=examples/carl_generalization_example/context_sets/train_contexts_a.json' '+env_kwargs.load_eval_contexts=examples/carl_generalization_example/context_sets/test_contexts.json' checkpoint=examples/carl_generalization_example/carl_cartpole_generalization_mode_c/seed_42/checkpoints/250000 output_dir=examples/carl_generalization_example experiment_name=carl_cartpole_generalization_mode_c/testing_seed